### ISSUE TITLE
Support CrystalLang 1.0.0

### ISSUE THREAD

**Issue by hholst80** [jeromegn/docker.cr#5]
```
- `crystal (< 1.0.0)` required by `docker 0.1.2`
```

**Comment by hholst80** [comment]
A reasonable workaround for now might be to include in shard.yml

```yaml
dependencies:
  json_mapping:
    github: crystal-lang/json_mapping.cr
```
